spring:
  datasource:
    url: jdbc:mysql://mysql:3306/nonconformity_db
    username: root
    password: changeme
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8085/realms/iso9001-realm

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: ${PORT:8081}

